root: ./packages/docs/

redirects:
  operations-manual/key-management/using-a-ledger-wallet: celo-gold-holders/ledger.md
  operations-manual/key-management/ledger: celo-gold-holders/ledger.md
  operations-manual/summary/ledger: celo-gold-holders/ledger.md
  operations-manual/using-a-ledger-wallet: celo-gold-holders/ledger.md
  getting-started/running-a-full-node.md: getting-started/running-a-full-node-in-baklava.md
  getting-started/running-a-validator.md: getting-started/running-a-validator-in-baklava.md
  getting-started/using-the-wallet.md: getting-started/using-the-mobile-wallet.md
